### ISSUE TITLE
Linker error on mac

### ISSUE THREAD

**Issue by joprice** [justbuchanan/bazel_rules_qt#3]
These rules don't seem to work on mac since the libraries are distributed as frameworks. Switching the linkopts to use frameworks like `"-framework QtCore"` and adding `build --linkopt=-F/usr/local/opt/qt5/lib` to `.bazelrc` makes it work.

**Comment by bedbad** [comment]
Do you have a version of qt bazel that works on Mac?

**Comment by Vertexwahn** [comment]
There is an attempt from my side to make Bazel rules Qt work with macOS. I am using `-framework QtCore` and `-F/usr/local/opt/qt5/lib` - the PR is here: https://github.com/justbuchanan/bazel_rules_qt/pull/38. But lead to a run time error: `dyld: Symbol not found: __ZN10QByteArray6_emptyE`

@joprice If you have a working version it would be nice if you could share it with us
@bedbad Maybe you can test the PR - maybe its only an issue on my machine

**Comment by Vertexwahn** [comment]
@justbuchanan I think this issue can be closed now

**Comment by justbuchanan** [comment]
@Vertexwahn thanks, done.
