### ISSUE TITLE
Windows: Cannot find uic

### ISSUE THREAD

**Issue by Vertexwahn** [justbuchanan/bazel_rules_qt#30]
I installed on my Windows 10 x64 (Version 20H2) system Qt via:

    python -m aqt install --outputdir C:\Qt 5.9.9 windows desktop win64_msvc2017_64

When doing 

     git clone https://github.com/justbuchanan/bazel_rules_qt.git
     cd bazel_rules_qt
     bazel build //...

I get the following error message:

    ERROR: G:/dev/bazel_rules_qt/tests/qt_ui_library/BUILD:3:14: Action tests/qt_ui_library/ui_mainwindow.h failed: (Exit -1): uic failed: error executing command uic tests/qt_ui_library/mainwindow.ui -o bazel-out/x64_windows-fastbuild/bin/tests/qt_ui_library/ui_mainwindow.h. Note: Remote connection/protocol failed with: execution failed
  Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("uic" tests/qt_ui_library/mainwindow.ui -o bazel-out/x64_windows-fastbuild/bin/tests/qt_ui_library/ui_mainwindow.h): Das System kann die angegebene Datei nicht finden.
   (error: 2)

I guess I have to add uic to the PATH environment variable.
Would be nice if this would work without adding uic to the environment variable

**Comment by justbuchanan** [comment]
Were you able to get this to work by adding the directory to your PATH?

**Comment by Vertexwahn** [comment]
Yes, I was able to get this fixed setting the PATH variable.

Nevertheless, I think it would be better if Qt would be fetched via Bazel. I currently work on an experiment. My plan is to upload prebuild versions of Qt to my homepage and fetch it from there, e.g.

```
def fetch_qt6():
    ### Qt 6.1.0

    # downloaded via  python -m aqt install windows desktop win64_msvc2019_64
    http_archive(
        name = "qt_6.1.0_windows_desktop_win64_msvc2019_64",
        urls = ["http://vertexwahn.de/lfs/v1/qt_6.1.0_windows_desktop_win64_msvc2019_64.zip"],
        sha256 = "705684b672bc4305435f5a78c80399aef08f0120623b59c02f1298339c93fab4",
        strip_prefix = "6.1.0/msvc2019_64",
        build_file = "//:qt_6.1.0_windows_desktop_win64_msvc2019_64.BUILD",
    )

    # downloaded via python -m aqt install 6.1.0 linux desktop gcc_64
    http_archive(
        name = "qt_6.1.0_linux_desktop_gcc_64",
        urls = ["http://vertexwahn.de/lfs/v1/qt_6.1.0_linux_desktop_gcc_64.tar.xz"],
        sha256 = "334dfabef8d98cf6e61db304b1ff8e892c7ea7a02f0e238014203161498ef5b9",
        strip_prefix = "6.1.0/gcc_64",
        build_file = "//:qt_6.1.0_linux_desktop_gcc_64.BUILD",
    )
```

For Windows also the "platform" folder has to be copied to the exeuctable dir:

```
load("@bazel_skylib//rules:copy_file.bzl", "copy_file")

def create_platfroms_folder():
    copy_file("qwindows.dll", src="@qt//:platform_files", out="platforms/qwindows.dll")
```
Not sure if I will finish this experiment. I will let you know once I have something that works.

I think for now the solution is to add Qt bin folder to PATH.
