### ISSUE TITLE
Rename QT_DIR

### ISSUE THREAD

**Issue by GabrielDougherty** [justbuchanan/bazel_rules_qt#35]
Hi, thank you for working on this project. I find the name for the environment variable QT_DIR to be confusing. It is very similar to the existing environment variable QTDIR. Its purpose is to override the path to the QT installation in the Bazel build, so I propose it to be renamed to BAZEL_RULES_QT_DIR. This makes it easier for someone reading e.g. a CI configuration to find out what the purpose of the environment variable is. Also, it does not conflict with any existing environment variables.

If you are open to this change, I can open a Pull Request.

**Comment by justbuchanan** [comment]
This sounds like a good idea to me. I'm open to renaming to `BAZEL_RULES_QT_DIR`. Thanks for the suggestion!
