### ISSUE TITLE
Rules not properly working with Windows

### ISSUE THREAD

**Issue by limdor** [justbuchanan/bazel_rules_qt#5]
More than a bug is a issue to share issue and ideas, not sure if you ever intended to make the rules work with Windows.

With the examples and the proposed solution I did not manage to make it work with windows, but maybe I am just missing something.

In Windows the concept of installing libraries you don't have it and it is not so easy to make it work with the cc_library targets that are in https://github.com/justbuchanan/bazel_rules_qt/blob/master/qt.BUILD

The best way that I found for the moment is to have them as cc_import https://github.com/limdor/quoniam/blob/master/dependencies/qt/BUILD.qt (for each there is two rules because of this bug https://github.com/bazelbuild/bazel/issues/4748)

The advantage with that is that you point to the root of the Qt installation, not just the include (https://github.com/limdor/quoniam/blob/master/WORKSPACE#L12) and then you could use the specific uic without the need of having it in the path.

This would also give the benefit that you can have two different installations of Qt for example 5.5 and 5.12 and just change the line in the workspace file being independent of what you have in your path.
Not sure my approach how would be to make it with linux in a unified way but I'll keep you posted.

**Comment by justbuchanan** [comment]
Hi Xavier, thanks for your interest in the project. So far my use of bazel+qt has been linux-only, so I haven't needed to get things working on Windows. However, I do expect to need Windows support for a project I'm working on and think it'd be a great addition.

Thanks for pointing out `cc_import` - I do think that's probably a good fit for this. We'll likely need to use the bazel "platforms" feature to set options differently on linux and windows: https://docs.bazel.build/versions/master/platforms.html.

The installation paths of libraries on linux vary by distro, but in general most libraries get put into the same directory. For example on my system, the qt4 core library is at `/usr/lib/x86_64-linux-gnu/libQtCore.so`. The qt5 lib is in the same directory, but named `libQt5Core.so`. So for linux, there isn't usually a "root of the qt installation".

I don't have a whole lot of time to work on adding Windows support right now, but I'm certainly happy to accept pull requests if you are able to get some things working. I can also add a windows build to the circleci config I have, which currently tests linux support.

**Comment by limdor** [comment]
I will fork it to try to make it work for Windows with my use case and then we can see how we can put it together. I am not really familiar with "platforms" feature and I think it will be easier to play around with a pure Windows option.
I am not sure how much time I will have also because I do it in my free time but I am motivated because I want to port a Qt project to Bazel and I need the rules.
I'll keep you posted on the status.

**Comment by limdor** [comment]
@justbuchanan I created a PR https://github.com/justbuchanan/bazel_rules_qt/pull/9 that adds windows support without breaking linux support. It could be that this is not complete to make windows work but it should not break the current linux integration.
Please let me know what you think.

**Comment by limdor** [comment]
To close the circle: I just updated my open source project that uses qt on windows and now it points to this repo. Everything seems to work https://github.com/limdor/quoniam/pull/81
Thanks a lot
