### ISSUE TITLE
How do I generate the implementation after uic'ing my .ui?

### ISSUE THREAD

**Issue by Joseph459459** [justbuchanan/bazel_rules_qt#8]
I would like to generate the .cc files for my .ui file using the qt_cc_library rule. It states
` If a UI file is provided, then it is also compiled with UIC.` 
I am not sure what arguments to put where - I have successfully generated the header file with qt_ui_library, though.

**Comment by Joseph459459** [comment]
When I try to target the generated header file in bazel-bin, there is an error that states that there can be no up-level references.

**Comment by justbuchanan** [comment]
Hi @Joe459 , could you share what your BUILD file looks like? I think the bazel rule you're looking for is [qt_ui_library](https://github.com/justbuchanan/bazel_rules_qt/blob/b293b5afd8772ef7de0069ad01a96e373535ee6e/qt.bzl#L20), which will generate source files for the uic and create a cc_library for it.

The documentation for `qt_cc_library` that mentioned .ui files was out of date, sorry about that. It's updated now.
